title: Pequenos Contos Vividos e Inventados
logo: /assets/img/logo.png
description: Este é o site de divulgação do projeto Pequenos Contos Vividos e Inventados no ar pela plataforma do Benfeitoria.  www.benfeitoria.com/vividoseinventados
google_analytics:
theme: jekyll-theme-minimal
